### ISSUE TITLE
parallel assignment in small_step/machine.rb

### ISSUE THREAD

**Issue by ghost** [tomstuart/computationbook#1]
Hello,
This may be a pebkac as my ruby is essentially non-existent, but when working through 'The Meaning of Programs' examples I notice that the parallel assignment in small_step/machine.rb step method:

self.statement, self.environment = statement.reduce(environment)

sets self.environment to nil after the first reduce:

?> Machine.new(
?> Add.new(Variable.new(:x), Variable.new(:y)),
?> {x: Number.new(3), y:Number.new(4)}).run
x + y, {:x=>«3», :y=>«4»}
3 + y,
NoMethodError: undefined method `[]' for nil:NilClass
        from /Users/rob/dev/ruby/computationbook/the_meaning_of_programs/small_step/variable.rb:9:in`reduce'
        from /Users/rob/dev/ruby/computationbook/the_meaning_of_programs/small_step/add.rb:13:in `reduce'
        from /Users/rob/dev/ruby/computationbook/the_meaning_of_programs/small_step/machine.rb:3:in`step'
        from /Users/rob/dev/ruby/computationbook/the_meaning_of_programs/small_step/machine.rb:9:in `run'
        from (irb):12
        from /usr/local/bin/irb:12:in`<main>'

I suppose reduce() should be returning the environment as well as the Number.
Hope this is useful feedback as I'm enjoying the book.

**Comment by tomstuart** [comment]
Sorry, yes, the `Machine` class in this repository is designed to reduce _statements_, not expressions. Calling `#reduce` on a reducible statement (`Assign`, `If`, `Sequence` or `While`) returns a two-element array containing the reduced statement and a new environment, which get assigned to `self.statement` and `self.environment` respectively in `Machine#step`. Reducing a reducible expression (`Add`, `LessThan`, `Multiply` or `Variable`) only returns another expression, not an environment, so it’s not suitable for use with this `Machine`.

The `Machine` class gets thrown away and redefined a couple of times throughout Chapter 2 as we introduce more complex kinds of syntax. The first version, which reduces basic _expressions_, appears early in the chapter (pp. 28–29):

``` ruby
class Machine < Struct.new(:expression)
  def step
    self.expression = expression.reduce
  end

  def run
    while expression.reducible?
      puts expression
      step
    end

    puts expression
  end
end
```

This is then redefined to support environments (i.e. to make `Variable` work) on page 32:

``` ruby
Object.send(:remove_const, :Machine) # forget about the old Machine class

class Machine < Struct.new(:expression, :environment)
  def step
    self.expression = expression.reduce(environment)
  end

  def run
    while expression.reducible?
      puts expression
      step
    end

    puts expression
  end
end
```

And then eventually redefined again to reduce _statements_ instead of expressions on page 36:

``` ruby
Object.send(:remove_const, :Machine)

class Machine < Struct.new(:statement, :environment)
  def step
    self.statement, self.environment = statement.reduce(environment)
  end

  def run
    while statement.reducible?
      puts "#{statement}, #{environment}"
      step
    end

    puts "#{statement}, #{environment}"
  end
end
```

This final version is the one that appears in this repo. Sorry for the confusion — these different definitions make sense in the context of the chapter, but perhaps I should’ve given them different class names (`ExpressionMachine`, `StatementMachine` etc) to make it possible to include all of them in the example code instead of just picking the final version.
